# Generated by Django 6.0.2 on 2026-03-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, choices=[('BLAGOEVGRAD', 'Благоевград'), ('BURGAS', 'Бургас'), ('VARNA', 'Варна'), ('VELIKO_TARNOVO', 'Велико Търново'), ('VIDIN', 'Видин'), ('VRATSA', 'Враца'), ('GABROVO', 'Габрово'), ('DOBRICH', 'Добрич'), ('KARDZHALI', 'Кърджали'), ('KYUSTENDIL', 'Кюстендил'), ('LOVECH', 'Ловеч'), ('MONTANA', 'Монтана'), ('PAZARDZHIK', 'Пазарджик'), ('PERNIK', 'Перник'), ('PLEVEN', 'Плевен'), ('PLOVDIV', 'Пловдив'), ('RAZGRAD', 'Разград'), ('RUSE', 'Русе'), ('SILISTRA', 'Силистра'), ('SLIVEN', 'Сливен'), ('SMOLYAN', 'Смолян'), ('SOFIA', 'София'), ('SOFIA_GRAD', 'София - град'), ('STARA_ZAGORA', 'Стара Загора'), ('TARGOVISHTE', 'Търговище'), ('HASKOVO', 'Хасково'), ('SHUMEN', 'Шумен'), ('YAMBOL', 'Ямбол')], max_length=20, null=True),
        ),
    ]
