# Generated by Django 6.0.3 on 2026-04-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
