# Generated by Django 6.0.3 on 2026-04-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('edit_report', 'Може да редактира отчет')], 'verbose_name': 'Събитие', 'verbose_name_plural': 'Събития'},
        ),
    ]
