# Generated by Django 6.0.3 on 2026-04-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Регистриран потребител', 'verbose_name_plural': 'Потребители'},
        ),
    ]
