# Generated by Django 6.0.3 on 2026-03-31 12:48

import django.core.validators
import django.db.models.deletion
import participants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('car_registration_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Регистрационният номер трябва да съдържа само главни латински букви и цифри (4–8 символа).', regex='^[A-Z0-9]{4,8}$')])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='participants/', validators=[participants.validators.validate_image])),
                ('appended_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.cities')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantEventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'event', 'role'), name='unique_participant_event_role')],
            },
        ),
    ]
