# Generated by Django 6.0.2 on 2026-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteventrole',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
