# Generated by Django 6.0.3 on 2026-03-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user_id',
            new_name='user',
        ),
    ]
