# Generated by Django 6.0.2 on 2026-03-29 20:45

import participants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_city_delete_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='participants/', validators=[participants.validators.validate_image]),
        ),
    ]
