# Generated by Django 6.0.3 on 2026-04-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_rename_user_id_participant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Доброволец', 'verbose_name_plural': 'Доброволци'},
        ),
        migrations.AlterModelOptions(
            name='participanteventrole',
            options={'verbose_name': 'Събитие, участник, роля', 'verbose_name_plural': 'Събития, участници, роли'},
        ),
    ]
