# Generated by Django 6.0.2 on 2026-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(choices=[('BLAGOEVGRAD', 'Благоевград'), ('BURGAS', 'Бургас'), ('VARNA', 'Варна'), ('VELIKO_TARNOVO', 'Велико Търново'), ('VIDIN', 'Видин'), ('VRATSA', 'Враца'), ('GABROVO', 'Габрово'), ('DOBRICH', 'Добрич'), ('KARDZHALI', 'Кърджали'), ('KYUSTENDIL', 'Кюстендил'), ('LOVECH', 'Ловеч'), ('MONTANA', 'Монтана'), ('PAZARDZHIK', 'Пазарджик'), ('PERNIK', 'Перник'), ('PLEVEN', 'Плевен'), ('PLOVDIV', 'Пловдив'), ('RUSE', 'Русе'), ('RAZGRAD', 'Разград'), ('SILISTRA', 'Силистра'), ('SLIVEN', 'Сливен'), ('SMOLYAN', 'Смолян'), ('SOFIA', 'София'), ('SOFIA_GRAD', 'София - град'), ('STARA_ZAGORA', 'Стара Загора'), ('TARGOVISHTE', 'Търговище'), ('HASKOVO', 'Хасково'), ('SHUMEN', 'Шумен'), ('YAMBOL', 'Ямбол')], max_length=20)),
            ],
        ),
    ]
