# Generated by Django 6.0.3 on 2026-04-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Град/Село', 'verbose_name_plural': 'Населени места'},
        ),
    ]
