# Generated by Django 6.0.2 on 2026-03-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='district',
            field=models.CharField(choices=[('BLAGOEVGRAD', 'Благоевград'), ('BURGAS', 'Бургас'), ('VARNA', 'Варна'), ('VELIKO_TARNOVO', 'Велико Търново'), ('VIDIN', 'Видин'), ('VRATSA', 'Враца'), ('GABROVO', 'Габрово'), ('DOBRICH', 'Добрич'), ('KARDZHALI', 'Кърджали'), ('KYUSTENDIL', 'Кюстендил'), ('LOVECH', 'Ловеч'), ('MONTANA', 'Монтана'), ('PAZARDZHIK', 'Пазарджик'), ('PERNIK', 'Перник'), ('PLEVEN', 'Плевен'), ('PLOVDIV', 'Пловдив'), ('RUSE', 'Русе'), ('RAZGRAD', 'Разград'), ('SILISTRA', 'Силистра'), ('SLIVEN', 'Сливен'), ('SMOLYAN', 'Смолян'), ('SOFIA', 'София'), ('SOFIA_GRAD', 'София - град'), ('STARA_ZAGORA', 'Стара Загора'), ('TARGOVISHTE', 'Търговище'), ('HASKOVO', 'Хасково'), ('SHUMEN', 'Шумен'), ('YAMBOL', 'Ямбол')], error_messages={'required': 'Моля изберете област.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(error_messages={'required': 'Моля въведете име на град или село.', 'unique': 'Такъв град вече съществува.'}, max_length=20, unique=True),
        ),
    ]
